---
- hosts: all
  become: true
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'golang', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install Docker-Compose Module for Python
      pip:
        name: docker-compose==1.25.0

    - name: Install PyYAML Module for Python
      pip:
        name: PyYAML

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.0/docker-compose-Linux-x86_64
        dest: "/usr/local/bin/docker-compose"
        mode: 0755

    - name: Deploy git Rrepository
      git:
        repo: https://github.com/florianakos/file-monitor-service.git
        dest: /home/flrnks/repo
        force: yes

    - name: Create and start service
      docker_compose:
        project_src: /home/flrnks/repo
        build: yes
